// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataBaseApiContext))]
    partial class DataBaseApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DynamicWPInformationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emergency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullyCustomizable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelpWithIntegration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricingMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("dynamicWPInformationModels");
                });

            modelBuilder.Entity("SmartHomeInformatioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emergency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelpWithIntegration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileAccessControl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelAdminDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricingMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("smarthomeInformationModel");
                });

            modelBuilder.Entity("SoftwareInformationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emergency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullyCustomizable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelpWithIntegration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricingMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("softwareInformationModels");
                });

            modelBuilder.Entity("StaticWPInformationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emergency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullyCustomizable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelpWithIntegration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricingMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("staticWPInformationModels");
                });
#pragma warning restore 612, 618
        }
    }
}
